# 数据路径配置
# data_path: "/home/hhr/home/InteractWeb-Bench/data/test_mini.jsonl"
#docker:
data_path: "/app/data/part1.jsonl"
# output_dir: "/home/hhr/home/store/experiment_results"
#docker:
output_dir: "/app/experiment_results"
# 模型选择配置
models:

  builder_model: "claude-sonnet-4-6"
  visual_copilot_model: "claude-sonnet-4-6"

  webvoyager_model: "gpt-5-mini"
  user_model: "deepseek-v3.2"
