# 数据路径配置
data_path: "/home/hhr/home/InteractWeb-Bench/data/test_mini.jsonl"
#docker:
#data_path: "/app/data/test_mini.jsonl"
output_dir: "/home/hhr/home/store/experiment_results"
#docker:
#output_dir: "/app/experiment_results"
# 模型选择配置
models:
  builder_model: "gpt-4.1"
  visual_copilot_model: "gpt-4.1"
  webvoyager_model: "gpt-5-mini"
  user_model: "deepseek-v3.2"
